pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key
static_host_map:
  "192.0.2.1":
    - "lighthouse.example.com:4242"
    - "198.51.100.10:4242"

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.0.2.1"

listen:
  host: 0.0.0.0
  port: 0

punchy: true
punch_back: true

local_range: "198.51.100.0/24"

tun:
  dev: nebula1

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  outbound:
    - proto: icmp
      host: any
      
  inbound:
    - proto: icmp
      host: any
    - port: 22
      proto: tcp
      host: any
